// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBFm-qq9GGPlvdAq2rtqysU26XTx_4HXw',
    appId: '1:1052749791149:web:8559e14f78252e6e162b24',
    messagingSenderId: '1052749791149',
    projectId: 'conversa-data',
    authDomain: 'conversa-data.firebaseapp.com',
    storageBucket: 'conversa-data.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4DWJNGJXkOnbbraoJXHth5yR_p9BO7s',
    appId: '1:1052749791149:android:e7b9868161b13fb6162b24',
    messagingSenderId: '1052749791149',
    projectId: 'conversa-data',
    storageBucket: 'conversa-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqf8lY-7Abd69BOYVRHpNJZ-uspWLJf_E',
    appId: '1:1052749791149:ios:63647737a393003a162b24',
    messagingSenderId: '1052749791149',
    projectId: 'conversa-data',
    storageBucket: 'conversa-data.firebasestorage.app',
    iosBundleId: 'com.romedev.converseGovData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqf8lY-7Abd69BOYVRHpNJZ-uspWLJf_E',
    appId: '1:1052749791149:ios:63647737a393003a162b24',
    messagingSenderId: '1052749791149',
    projectId: 'conversa-data',
    storageBucket: 'conversa-data.firebasestorage.app',
    iosBundleId: 'com.romedev.converseGovData',
  );
}
